version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: pyre-check
    versions:
    - 0.0.62
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: swagger-ui
  groups:
    react:
      patterns:
        - "react"
        - "react-dom"
        - "@types/react"
        - "@types/react-dom"
    mui:
      patterns:
        - "@mui/*"
- package-ecosystem: npm
  directory: "/pwa"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    update-types:
      - version-update:semver-major
  labels:
    - PWA
  groups:
    tanstack:
      patterns:
        - "@tanstack/*"
    embla-carousel:
      patterns:
        - "embla-carousel-autoplay"
        - "embla-carousel-react"
    radix-ui:
      patterns:
        - "@radix-ui/*"
    vite:
      patterns:
        - "vite"
        - "vite-tsconfig-paths"
        - "vitest"
        - "@vitest/coverage-v8"
        - "@julr/vite-plugin-validate-env"
        - "@vitejs/plugin-react"
        - "babel-plugin-react-compiler"
    linting:
      patterns:
        - "@eslint/*"
        - "eslint"
        - "eslint-config-prettier"
        - "eslint-import-resolver-typescript"
        - "eslint-plugin-import"
        - "eslint-plugin-jsx-a11y"
        - "eslint-plugin-no-relative-import-paths"
        - "eslint-plugin-react"
        - "eslint-plugin-react-hooks"
        - "globals"
        - "typescript-eslint"
        - "@typescript-eslint/*"
        - "prettier"
        - "prettier-plugin-classnames"
        - "prettier-plugin-merge"
        - "prettier-plugin-tailwindcss"
        - "@trivago/prettier-plugin-sort-imports"
    sentry:
      patterns:
        - "@sentry/*"
    tailwind:
      patterns:
        - "@tailwindcss/*"
        - "tailwindcss"
        - "tailwind-merge"
        - "tw-animate-css"
    icons:
      patterns:
        - "@iconify/json"
        - "lucide-react"
        - "unplugin-icons"
    react:
      patterns:
        - "react"
        - "react-dom"
        - "@types/react"
        - "@types/react-dom"
        - "react-intersection-observer"
    firebase:
      patterns:
        - "firebase"
        - "firebase-admin"
    testing:
      patterns:
        - "@playwright/test"
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
