version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: pyre-check
    versions:
    - 0.0.62
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: swagger-ui
  - dependency-name: firebase
    versions:
    - 8.4.0
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.13.0
- package-ecosystem: npm
  directory: "/pwa"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@sentry/*"
  labels:
    - PWA
  groups:
    react-router:
      patterns:
        - "@react-router/*"
        - "react-router"
    embla-carousel:
      patterns:
        - "embla-carousel-autoplay"
        - "embla-carousel-react"
    radix-ui:
      patterns:
        - "@radix-ui/*"
    vite:
      patterns:
        - "vite"
        - "vite-tsconfig-paths"
        - "vitest"
        - "@vitest/coverage-v8"
        - "@julr/vite-plugin-validate-env"
    linting:
      patterns:
        - "@eslint/*"
        - "eslint"
        - "eslint-config-prettier"
        - "eslint-import-resolver-typescript"
        - "eslint-plugin-import"
        - "eslint-plugin-jsx-a11y"
        - "eslint-plugin-no-relative-import-paths"
        - "eslint-plugin-react"
        - "eslint-plugin-react-hooks"
        - "globals"
        - "typescript-eslint"
        - "@typescript-eslint/*"
        - "prettier"
        - "prettier-plugin-classnames"
        - "prettier-plugin-merge"
        - "prettier-plugin-tailwindcss"
    sentry:
      patterns:
        - "@sentry/*"
    tailwind:
      patterns:
        - "@tailwindcss/*"
        - "tailwindcss"
        - "tailwind-merge"
        - "tw-animate-css"
    icons:
      patterns:
        - "@iconify/json"
        - "lucide-react"
        - "unplugin-icons"
    react:
      patterns:
        - "react"
        - "react-dom"
        - "@types/react"
        - "@types/react-dom"
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
