repos:
- repo: local
  hooks:
    # These run on the default stages (pre-commit)
    - id: py3-deps
      name: "[py3] venv Dependencies"
      always_run: true
      language: script
      entry: ./ops/check_venv_deps.sh
      stages: [pre-commit]
    - id: py3-type
      name: "[py3] Type Checking"
      types: [file, python]
      entry: ./ops/typecheck_py3.sh
      language: script
      stages: [pre-commit]
    - id: py3-lint
      name: "[py3] Formatting & Linting"
      types: [file, python]
      entry: ./ops/lint_py3.sh --fix
      language: script
      stages: [pre-commit]
    - id: py3-test
      name: "[py3] Testing"
      types: [file, python]
      entry: ./ops/test_py3.sh --relevant
      language: script
      stages: [pre-commit]
    - id: node-lint
      name: "[node] Formatting & Linting"
      types: [file, javascript]
      entry: ./ops/lint_node.sh --fix
      language: script
      stages: [pre-commit]
    - id: node-test
      name: "[node] Testing"
      types: [file, javascript]
      entry: ./ops/test_node.sh
      language: script
      stages: [pre-commit]
    - id: bash-lint
      name: "[bash] Formatting & Linting"
      types: [file, shell]
      entry: ./ops/lint_bash.sh
      language: script
      stages: [pre-commit]


    # These run as post-checkout
    - id: py3-deps
      name: "[py3] Updating dependencies"
      entry: ./ops/update_venv_deps.sh
      language: script
      always_run: true
      stages: [post-checkout]
    - id: gcloud-sdk-version
      name: "Checking Google Cloud SDK Version"
      entry: ./ops/check_sdk_version.sh
      language: script
      always_run: true
      stages: [post-checkout]


