x-shared_environment: &shared_environment
  IS_DOCKER: true

services:
  tba:
    # image: ghcr.io/the-blue-alliance/the-blue-alliance/tba-py3-dev:latest
    build:
      context: ./
      dockerfile: ./ops/dev/docker/Dockerfile
    volumes:
      - ./:/tba:delegated
    tty: true
    stdin_open: true
    ports:
      # GAE
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"
      - "8083:8083"
      - "8084:8084"
      - "8085:8085"
      - "8086:8086"
      - "8087:8087"
      - "8088:8088"
      - "8089:8089"
      # GAE Admin
      - "8000:8000"
    entrypoint: [ "sh", "/tba/ops/dev/docker/docker-entry.sh" ]
    command: [ "/usr/sbin/sshd", "-D" ]
    working_dir: /tba
    hostname: tba
    environment:
      <<: *shared_environment
      PUPPETEER_SKIP_DOWNLOAD: "true"
  firebase:
    build:
      context: ./ops/dev/docker/firebase_emulator
      dockerfile: Dockerfile
      args:
        - FIREBASE_VERSION=13.3.0
    stop_grace_period: 1m
    environment:
      <<: *shared_environment
      FIREBASE_PROJECT: "demo-test"
    healthcheck:
      test: ["CMD-SHELL", "curl -f -s http://localhost:9099 | jq -e '.authEmulator.ready'"]
      interval: 2s
      timeout: 2s
      retries: 10
      start_period: 5s
    ports:
      # Firebase
      - "4000:4000"
      - "4400:4400"
      - "4500:4500"
      - "9005:9005"
      - "9000:9000"
      - "9099:9099"
    hostname: firebase
    command: ["/firebase/run_firebase_emulator.sh"]
  firebase-bootstrap:
    build:
      context: ./ops/dev/docker/firebase_emulator
      dockerfile: Dockerfile
      args:
        - FIREBASE_VERSION=13.3.0
    environment:
      <<: *shared_environment
      FIREBASE_PROJECT: "demo-test" # TODO: Needs to be not hardcoded
    depends_on:
      firebase:
        condition: service_healthy
    restart: "no"
    hostname: firebase-bootstrap
    command: ["node", "/firebase/create_firebase_emulator_auth_accounts.js"]