x-env-vars: &env-vars
  PROJECT_ID: demo-test

services:
  firebase:
    build:
      context: ./
      dockerfile: ./ops/dev/firebase/Dockerfile.firebase
    environment:
      <<: *env-vars
    ports:
      - "4000:4000"
      - "4400:4400"
      - "4500:4500"
      - "9005:9005"
      - "9000:9000"
      - "9099:9099"

  datastore:
    build:
      context: ./
      dockerfile: ./ops/dev/datastore/Dockerfile.datastore
    environment:
      <<: *env-vars
    ports:
      - "8089:8089"
    volumes:
      - datastore-data:/data/datastore
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8089/"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  tba:
    build:
      context: ./
      dockerfile: ./ops/dev/docker/Dockerfile
    depends_on:
      firebase:
        condition: service_started
      datastore:
        condition: service_healthy
    volumes:
      - ./:/tba:delegated
    ports:
      # GAE
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"
      - "8083:8083"
      - "8084:8084"
      - "8085:8085"
      - "8086:8086"
      - "8087:8087"
      - "8088:8088"
      # GAE Admin
      - "8000:8000"
    working_dir: /tba
    hostname: tba
    environment:
      - DATASTORE_EMULATOR_HOST=datastore:8089
      - FIREBASE_AUTH_EMULATOR_HOST=firebase:9099
      - FIREBASE_DATABASE_EMULATOR_HOST=firebase:9000

  webpack:
    build:
      context: ./
      dockerfile: ./ops/dev/webpack/Dockerfile.webpack
    volumes:
      - ./:/tba:delegated
    working_dir: /tba
    environment:
      - WATCH=true

  ### Tools

  lint-bash:
    build:
      context: ./
      dockerfile: ./ops/dev/docker/Dockerfile.lint_bash
    profiles: ["tools"]
    volumes:
      - ./:/tba:delegated
    entrypoint:
      - /bin/bash
      - -c
      - './ops/lint_bash.sh "$@"'
      - --

volumes:
  datastore-data:
